import type { Meta, StoryObj } from '@storybook/react';
import { MusicPlaybackPhase } from './MusicPlaybackPhase';
import { PlayerSongSubmission } from '@/types/round'; // Use the correct type
import { fn } from '@storybook/test';

// Removed unused mock data generation helpers
// Mock Submitted Songs - Using PlayerSongSubmission structure
// Data generated by `npm run generate-mocks` script
// Data generated by `npm run generate-mocks` script (using Deezer)
// Note: PlayerSongSubmission type might need adjustment if deezerTrackId is used elsewhere
const mockDeezerSongs: PlayerSongSubmission[] = [
  { trackId: '3135556', name: 'Harder, Better, Faster, Stronger', artist: 'Daft Punk', preview_url: 'https://cdnt-preview.dzcdn.net/api/1/1/c/4/d/0/c4d7dbe3524ba59d2ad06d8cccd2484f.mp3?hdnea=exp=1743976328~acl=/api/1/1/c/4/d/0/c4d7dbe3524ba59d2ad06d8cccd2484f.mp3*~data=user_id=0,application_id=42~hmac=0438fc39318bd529e895a585394941ac605c1d747505cd1157e1611bd18615ca', albumImageUrl: 'https://cdn-images.dzcdn.net/images/cover/5718f7c81c27e0b2417e2a4c45224f8a/56x56-000000-80-0-0.jpg' },
  { trackId: '98244132', name: 'Drank & Drugs', artist: 'Lil Kleine', preview_url: 'https://cdnt-preview.dzcdn.net/api/1/1/7/8/2/0/782554067764f6455484bb526e45ea64.mp3?hdnea=exp=1743976328~acl=/api/1/1/7/8/2/0/782554067764f6455484bb526e45ea64.mp3*~data=user_id=0,application_id=42~hmac=0a7b6979eb7052a2066a996abeb6c6b4b2334cae463e5e6d4064ddfbc5adbac9', albumImageUrl: 'https://cdn-images.dzcdn.net/images/cover/003bbfb6bb04600d5076d9347e59e6d0/56x56-000000-80-0-0.jpg' },
  { trackId: '2292998895', name: 'Drank in Systeem', artist: 'Kleine John', preview_url: 'https://cdnt-preview.dzcdn.net/api/1/1/8/0/1/0/801ac3f72a9b131896b5c842a00c101a.mp3?hdnea=exp=1743976328~acl=/api/1/1/8/0/1/0/801ac3f72a9b131896b5c842a00c101a.mp3*~data=user_id=0,application_id=42~hmac=6b2b4d2ff4a69c18ab03f0e0038e6428b7936fd87749518ce2c90b4fd67c1d7e', albumImageUrl: 'https://cdn-images.dzcdn.net/images/cover/f9716b5f5b01fece8731a77adda172b0/56x56-000000-80-0-0.jpg' },
  { trackId: '1141065582', name: 'Drankin N Smokin', artist: 'Future', preview_url: 'https://cdnt-preview.dzcdn.net/api/1/1/2/8/7/0/287eb2dc61aa75c65c8e6235c695da33.mp3?hdnea=exp=1743976329~acl=/api/1/1/2/8/7/0/287eb2dc61aa75c65c8e6235c695da33.mp3*~data=user_id=0,application_id=42~hmac=8b5e5d22c302cad9189214ab255aa119bd19542384ef99aed881caa18d03de98', albumImageUrl: 'https://cdn-images.dzcdn.net/images/cover/92c4fd7ad32051203b4c27567174ccff/56x56-000000-80-0-0.jpg' },
  { trackId: '914866', name: 'Drank Vannacht', artist: 'The Opposites', preview_url: 'https://cdnt-preview.dzcdn.net/api/1/1/7/e/7/0/7e7e5364c3fd6326560aaf8c29516842.mp3?hdnea=exp=1743976329~acl=/api/1/1/7/e/7/0/7e7e5364c3fd6326560aaf8c29516842.mp3*~data=user_id=0,application_id=42~hmac=d65a0b881f219cc37199852084759e9245f3f69405b68207b36285f2d7aca074', albumImageUrl: 'https://cdn-images.dzcdn.net/images/cover/2120f48ddd7f031fa90d886d9aafb108/56x56-000000-80-0-0.jpg' }
];
// Removed mock helpers for Artist, Image, Album as they are not directly used by PlayerSongSubmission

// Removed basePlaybackState as it's no longer used

const meta = {
  title: 'Game Phases/MusicPlaybackPhase',
  component: MusicPlaybackPhase,
  parameters: {
    layout: 'padded',
    docs: {
        description: {
            component: 'Displays controls for listening to submitted songs using HTML audio previews. Playback is synchronized and controlled by the host.'
        },
    }
  },
  tags: ['autodocs'],
  argTypes: { // Updated argTypes for new props
    gameId: { control: 'text' },
    playerId: { control: 'text' },
    isHost: { control: 'boolean' },
    currentRound: { control: 'number' },
    submittedSongs: { control: 'object' },
    currentPlayingTrackIndex: { control: 'number' },
    isPlaying: { control: 'boolean' },
    // Removed old SDK-related argTypes
  },
  args: { // Default args for the new component structure
    gameId: 'test-game',
    playerId: 'player-1',
    isHost: true, // Default to host view
    currentRound: 4,
    submittedSongs: mockDeezerSongs, // Use the new Deezer mock data
    currentPlayingTrackIndex: 0, // Start with the first track selected
    isPlaying: false, // Start paused
  },
} satisfies Meta<typeof MusicPlaybackPhase>;

export default meta;
type Story = StoryObj<typeof meta>;

// Removed PlayerInitializing story as it's not relevant to HTML audio

export const HostViewPaused: Story = {
    name: "Host View / Paused",
    args: {
      isHost: true,
      isPlaying: false,
      currentPlayingTrackIndex: 0,
    },
};

export const HostViewPlayingTrack1: Story = {
    name: "Host View / Playing Track 1",
    args: {
        isHost: true,
        isPlaying: true,
        currentPlayingTrackIndex: 0, // Index of 'Dancing Queen'
    },
};

export const HostViewPlayingTrack3NoPreview: Story = {
    name: "Host View / Playing Track 3 (No Preview)",
    args: {
        isHost: true,
        isPlaying: true, // Still "playing" state, but button disabled
        currentPlayingTrackIndex: 2, // Index of 'Stayin' Alive'
    },
};

export const NonHostViewPlaying: Story = {
    name: "Non-Host View / Playing",
    args: {
        isHost: false,
        isPlaying: true,
        currentPlayingTrackIndex: 1, // Index of 'September'
    },
};

export const NonHostViewPaused: Story = {
    name: "Non-Host View / Paused",
    args: {
        isHost: false,
        isPlaying: false,
        currentPlayingTrackIndex: 1,
    },
};

// Removed PlaybackError story as HTML audio errors are handled differently

export const NoSongsSubmitted: Story = {
    name: "State: No Songs Submitted",
    args: {
        submittedSongs: [],
        currentPlayingTrackIndex: 0,
        isPlaying: false,
    },
};